# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vWRiVvTVpBn5BuvO5DBhX8qtdFob_irA
"""

#!apt-get install libgmp-dev libmpfr-dev libmpc-dev

#!pip install gmpy2==2.1.0a2



import gmpy2 as gm
from gmpy2 import mpz,mul,next_prime,gcd,invert,powmod

p=mpz(input())
q=mpz(input())
m=mpz(input())

n=mul(p,q)
psy=mul(p-1,q-1)
#print(n)
#print(psy)
#e=[2,psy-1] and is coprime with psy

e=next_prime(q)
d=invert(e,psy)
c=powmod(m,e,n)
m=powmod(c,d,n)
print(c)
print(e)
print(d)
print(n)

